### ISSUE TITLE
Throwing exceptions instead of rendering an error message

### ISSUE THREAD

**Issue by quasicomputational** [mathjax/MathJax-demos-node#25]
I'm trying to use MathJax as a server-side renderer, patterened on the 'direct' styles of [`tex2svg`](https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2svg) and [`tex2mml`](https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2mml).

The normal case is working nicely enough - I put TeX in one end and I get MathML and SVG out the other! Pretty great.

However, if the TeX is wrong somehow (e.g., an undefined control sequence), MathJax is happy to render *that* as well, except as an error message. I would much, much prefer an exception to be thrown, because this is a problem I would like to discover at build time (since it is *always* indicating an error that requires correction), not whenever I happen to check the rendered result manually (or, more likely, someone points out to me that everything has been broken for six months and I've not noticed...).

Is there some setting I could toggle to get MathJax to fail hard, preferably by throwing an exception? My current best idea for a workaround is to walk the MathML tree and look for a `data-mjx-error` attribute, which seems ugly and fragile.

**Comment by quasicomputational** [comment]
I've just seen that #3 is covering exactly this ground, which solves my immediate problem.

Seeing that two people have stubbed their toe on this, maybe the (great) write-up from #3 ought to be put somewhere more prominently - possibly in an example so it's copy-and-paste ready?

**Comment by dpvc** [comment]
There is actually an easier way to do it, now.  We added a `formatError` configuration option so that you can provide your own routine for handgun the errors.  You could simply throw the error from there, as in the "most elegant" example you link to.  So you should be able to do

``` html
<script>
MathJax = {
  tex: {
    formatError(jax, error) {
      throw Error('TeX error: ' + error.message);
    }
  }
};
</script>
```

to get the effect you are looking for.  See the [v3.1 release notes](https://docs.mathjax.org/en/latest/upgrading/whats-new-3.1.html#tex-error-formatting) for information about this new configuration option.
