### ISSUE TITLE
How to use mathjax tex2svg-page without separate components?

### ISSUE THREAD

**Issue by brunobmello25** [mathjax/MathJax-demos-node#47]
Looking at [this repository](https://github.com/mathjax/MathJax-demos-node) it mentions how to use mathjax separate components to customize the way I want, but it doesn't mention what package I need to import if I want to use just the basics of tex2svg-page. 

Additionally, it doesn't specify how can I setup a custom inline math selector, like the way we do on the client side:

```
window.MathJax = {
              tex: {
                inlineMath: [
                  [
                    '$', '$'
                  ]
                ],
            };
```

**Comment by dpvc** [comment]
The code for all the examples are available in this repository.  But since there are several different ways to include MathJax, depending on your needs, the examples are broken down by the mechanism used.  You probably want to component-based examples, such as [`tex2svg-page`](https://github.com/mathjax/MathJax-demos-node/blob/master/component/tex2svg-page).  You may not need all the command-line processing, so some simplification is possible.  See the [main README](https://github.com/mathjax/MathJax-demos-node/tree/master/component#component-based-examples) for the high-level description of how all the examples in the components directory work.

The key lines are

https://github.com/mathjax/MathJax-demos-node/blob/6ffe55730e6146781f0404abd628e90669b7c138/component/tex2svg-page#L92-L110

Line 95 could be simplified to

``` js
require('mathjax-full/es5/tex-svg.js');
```

and

https://github.com/mathjax/MathJax-demos-node/blob/6ffe55730e6146781f0404abd628e90669b7c138/component/tex2svg-page#L103-L107

are just to handle case where the page has no math in it (so that the unneeded CSS styles aren't included), so you might be able to remove those as well.  What's left, together with the configuration, is the code you need to have MathJax process a page for you.  Be sure to read about the configuration in the README linked above.
