### ISSUE TITLE
let wrapper = MathJax.tex2svg('y', {display: true});  字符y获取到的svg，右上角缺少

### ISSUE THREAD

**Issue by szdenny2** [mathjax/MathJax-demos-node#61]
function exportSVG() {
            try {
                let outputdiv = document.getElementById('output');  // 添加变量声明
                let wrapper = MathJax.tex2svg('y', {display: true});
                let svg = wrapper.getElementsByTagName("svg")[0];
                // 设置前景色
                const pathList = Array.from(svg.getElementsByTagName("path"));
                pathList.forEach(i => {
                    i.setAttribute("fill", "#0167fe");
                });
                const rectList = Array.from(svg.getElementsByTagName("rect"));
                rectList.forEach(i => {
                    i.setAttribute("fill", "#0167fe");
                });
                //console.log(svg.outerHTML);
                //渲染svg到网页上
                document.body.appendChild(svg)
                //return svg.outerHTML;  // 返回生成的 SVG
            } catch (error) {
                console.log(error);
                window.chrome.webview.postMessage(error);
            }
        }

**Comment by dpvc** [comment]
There is not enough information here to resolve your issue.  What version of MathJax are you using (full version please)?  Which MathJax `.js` file are you loading?  What is your MathJax configuration, if any?  Can you provide a screen shot of the result you are seeing?

Most important, have you included into your page the CSS that MathJax's SVG output jax generates?  In particular, there is CSS that controls the clipping of the SVG elements (it turns off the default clipping to the `viewBox`), and that may be what is causing your situation.  You might try adding

``` js
svg.style.overflow = "visible";
```

Also, you are working too hard to set the color of the mathematics, and it may have adverse consequences (there are some `rect` elements that should *not* be filled, for example, and some elements whose fill color should not be changed).  It would be easier to do

``` js
const svg = wrapper.getElementsByTagName("svg")[0];
const g = svg.querySelector('g[stroke="currentColor"]');
g.setAttribute('stroke', '#0167fe');
g.setAttribute('fill', '#0167fe');
```

and that should do it.

Finally, if you are not going to be including the MathJaX CSS, you may want to embed a minimal stylesheet in the SVG itself.  For example, you could do

``` js
const svg = wrapper.getElementsByTagName("svg")[0];
const g = svg.querySelector('g[stroke="currentColor"]');
g.setAttribute('stroke', '#0167fe');
g.setAttribute('fill', '#0167fe');
const styles = document.createElement('style');
styles.textContent = [
  'svg a{fill:blue;stroke:blue}',
  '[data-mml-node="merror"]>g{fill:red;stroke:red}',
  '[data-mml-node="merror"]>rect[data-background]{fill:yellow;stroke:none}',
  '[data-frame],[data-line]{stroke-width:70px;fill:none}',
  '.mjx-dashed{stroke-dasharray:140}',
  '.mjx-dotted{stroke-linecap:round;stroke-dasharray:0,140}',
  'use[data-c]{stroke-width:3px}'
].join('');
svg.insertBefore(styles, g);
```

See, for example, the [tex2svg](https://github.com/mathjax/MathJax-demos-node/blob/master/component/tex2svg) example code.

**Comment by szdenny2** [comment]
找到原因了，是生成的svg图片的viewbox节点有问题，生成的数据；
<svg xmlns="http://www.w3.org/2000/svg" width="1.33ex" height="1.757ex" role="img" focusable="false" viewBox="0 -530.4 588 776.4" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" style="vertical-align: -0.557ex;"><defs><path id="MJX-1-TEX-I-1D466" d="M21 287Q21 301 36 335T84 406T158 442Q199 442 224 419T250 355Q248 336 247 334Q247 331 231 288T198 191T182 105Q182 62 196 45T238 27Q261 27 281 38T312 61T339 94Q339 95 344 114T358 173T377 247Q415 397 419 404Q432 431 462 431Q475 431 483 424T494 412T496 403Q496 390 447 193T391 -23Q363 -106 294 -155T156 -205Q111 -205 77 -183T43 -117Q43 -95 50 -80T69 -58T89 -48T106 -45Q150 -45 150 -87Q150 -107 138 -122T115 -142T102 -147L99 -148Q101 -153 118 -160T152 -167H160Q177 -167 186 -165Q219 -156 247 -127T290 -65T313 -9T321 21L315 17Q309 13 296 6T270 -6Q250 -11 231 -11Q185 -11 150 11T104 82Q103 89 103 113Q103 170 138 262T173 379Q173 380 173 381Q173 390 173 393T169 400T158 404H154Q131 404 112 385T82 344T65 302T57 280Q55 278 41 278H27Q21 284 21 287Z"></path></defs><g stroke="currentColor" fill="#0167fe" stroke-width="0" transform="scale(1,-1)"><g data-mml-node="math" fill="#0167fe"><g data-mml-node="mstyle" transform="scale(1.2)" fill="#0167fe"><g data-mml-node="TeXAtom" data-mjx-texclass="ORD" fill="#0167fe"><g data-mml-node="mi" fill="#0167fe"><use data-c="1D466" xlink:href="#MJX-1-TEX-I-1D466"></use></g></g></g></g></g></svg>

修改后的数据：
<svg xmlns="http://www.w3.org/2000/svg" width="1.33ex" height="1.757ex" role="img" focusable="false" viewBox="0 -530.4 598 776.4" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" style="vertical-align: -0.557ex;"><defs><path id="MJX-1-TEX-I-1D466" d="M21 287Q21 301 36 335T84 406T158 442Q199 442 224 419T250 355Q248 336 247 334Q247 331 231 288T198 191T182 105Q182 62 196 45T238 27Q261 27 281 38T312 61T339 94Q339 95 344 114T358 173T377 247Q415 397 419 404Q432 431 462 431Q475 431 483 424T494 412T496 403Q496 390 447 193T391 -23Q363 -106 294 -155T156 -205Q111 -205 77 -183T43 -117Q43 -95 50 -80T69 -58T89 -48T106 -45Q150 -45 150 -87Q150 -107 138 -122T115 -142T102 -147L99 -148Q101 -153 118 -160T152 -167H160Q177 -167 186 -165Q219 -156 247 -127T290 -65T313 -9T321 21L315 17Q309 13 296 6T270 -6Q250 -11 231 -11Q185 -11 150 11T104 82Q103 89 103 113Q103 170 138 262T173 379Q173 380 173 381Q173 390 173 393T169 400T158 404H154Q131 404 112 385T82 344T65 302T57 280Q55 278 41 278H27Q21 284 21 287Z"></path></defs><g stroke="currentColor" fill="#0167fe" stroke-width="0" transform="scale(1,-1)"><g data-mml-node="math" fill="#0167fe"><g data-mml-node="mstyle" transform="scale(1.2)" fill="#0167fe"><g data-mml-node="TeXAtom" data-mjx-texclass="ORD" fill="#0167fe"><g data-mml-node="mi" fill="#0167fe"><use data-c="1D466" xlink:href="#MJX-1-TEX-I-1D466"></use></g></g></g></g></g></svg>

**Comment by dpvc** [comment]
The `viewBox` attribute is based on the advance width of the character(s) within the expression.  Characters can extend beyond their advance width (for example, the italic "f" does this, as do most of the script letters from `\mathscr`, and the integral sign is an extreme case, where about half the glyph extends beyond its advance width).  The width of the SVG is supposed to be the width of the typeset expression (the sum of the advance widths of the characters used), that way, it will take up the same horizontal space as it would when typeset in TeX (or in MathJax's CHTML output).  So that means the characters may extend beyond with width of the SVG.

In your case, the advance width of the "y" in the font metrics for this character is slightly less than the extent of the "ink" for the character:

<img width="411" alt="y-metrics" src="https://github.com/mathjax/MathJax-demos-node/assets/432782/610c6e38-91f6-4f07-90d9-4aa69ab8c371">

(This is the character design window in FontForge for the "y").  That means the "y" extends slightly past the width of the SVG:

<img width="264" alt="y-image" src="https://github.com/mathjax/MathJax-demos-node/assets/432782/3db1f260-630a-44ab-8563-a3a6222e539a">

(This is your SVG file with an extra `rect` element that is the size of the `viewBox`.)

This is the intended behavior, so the `viewBox` is correct in this SVG.  The `viewBox` does not have to be a bounding box, and is not in this case.  (That is why I suggested you set the overflow CSS style.)  Note that there is space at the left of the "y" within the `viewBox` as well (just as there is space to the left of the "y" in the font metrics -- this is called "left bearing").  So this is clearly not a tight bounding box.  If you want such a bounding box, you will need to use the SVG command `getBBox()`, probably on the top-level `g` element, and use that to replace the `viewBox` values.  But if you do that, you will need to change the `height` and `width` attributes and the `vertical-align` CSS value to match he new `viewBox`, since they are based on the original `viewBox`.

**Comment by szdenny2** [comment]
Thanks for your reply, I get the viewBox of the g element, and use that to update the svg viewBox property values, and the problem is solved.

**Comment by dpc0828** [comment]
> 谢谢您的回复，我获取了g元素的viewBox，并使用它来更新svg viewBox属性值，问题就解决了。

能帖一下代码？我是一个后端，看不太懂怎么实现的

**Comment by dpc0828** [comment]
> 谢谢您的回复，我获取了g元素的viewBox，并使用它来更新svg viewBox属性值，问题就解决了。

我用命令行生成svg的时候也碰到这个问题了
