### ISSUE TITLE
Making a standalone minified script

### ISSUE THREAD

**Issue by astoff** [mathjax/MathJax-demos-node#66]
Hi, I'm trying to build the `mml2svg` script as a self-contained minified JS file for Node.

I've created a minimal Webpack configuration and my setup works when applied to [preload/tex2svg](https://github.com/mathjax/MathJax-demos-node/blob/master/preload/tex2svg). But when I run the same procedure on [preload/mml2svg](https://github.com/mathjax/MathJax-demos-node/blob/master/preload/mml2svg), the resulting minified script fails with the following error:

```
$ node mml2svg-min.js 
node:internal/modules/cjs/loader:1222
  throw err;
  ^

Error: Cannot find module 'xmldom-sre'
Require stack:
- /tmp/mml2svg-min.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at SystemExternal.extRequire (/tmp/mml2svg-min.js:1:1692029)
    at 4094 (/tmp/mml2svg-min.js:1:1692325)
    at __webpack_require__ (/tmp/mml2svg-min.js:1:2107164)
    at 6344 (/tmp/mml2svg-min.js:1:1671281) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tmp/mml2svg-min.js' ]
}

Node.js v22.4.1
```

How can I ensure that `xmldom-sre` is bundled inside the minified JS? I naively tried to add `require("xmldom-sre")` to the script but that didn't help.

**Comment by dpvc** [comment]
The `xmldom-sre` (as well as several other packages) are only used by node applications, and since webpack is usually used for making MathJax browser libraries, the speech-rule-engine (SRE) is set up specifically NOT to pack these modules.  

The easiest way around this would be to edit the `node_modules/speech-rule-engine/js/common/system_external.js` file and replace `SystemExternal.extRequire` by `require` in the four places that it is used.

If you don't want to edit a file in node_modules, you could copy that file to another location and edit it there, and include a `webpack.NormalModuleReplacementPlugin` in the `plugins` array of your configuration that redirects the `system_external.js` file to your modified one.

**Comment by astoff** [comment]
Thanks, this works indeed.
